apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../../kompose --file docker-compose.yml convert --chart
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: smtp
  name: smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: smtp
  template:
    metadata:
      annotations:
        kompose.cmd: ../../kompose --file docker-compose.yml convert --chart
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: smtp
    spec:
      containers:
        - env:
            - name: TZ
              value: EUROPE/PARIS
          image: dockage/mailcatcher:latest
          name: smtp
          ports:
            - containerPort: 1025
              protocol: TCP
            - containerPort: 1080
              protocol: TCP
      restartPolicy: Always
